source ./scripts/halfhalf.tcl
source ./scripts/cambiablocco.tcl
source ./scripts/mazzi.tcl
source ./scripts/paciocca.tcl
source ./scripts/cambiacar.tcl
source ./scripts/random.tcl
source ./scripts/randString.tcl
source ./scripts/cells_swapping.tcl
source ./scripts/mazziPowa.tcl
source ./scripts/genetics.tcl
genetics 2
